import fs from 'node:fs/promises'
import path from 'node:path'

const root = process.cwd()
const outputDir = path.resolve(root, process.env.MIGRATION_OUTPUT || 'migration-output')
const dataPath = path.join(outputDir, 'page-data.json')
const cssPath = path.join(outputDir, 'cleaned-runtime-css.css')
const targetCssPath = path.resolve(root, 'app/assets/css/extracted.css')
const manifestPath = path.resolve(root, 'public/asset-manifest.json')

function uniqueBy(array, keyFn) {
  const seen = new Set()
  const result = []
  for (const item of array) {
    const key = keyFn(item)
    if (!key || seen.has(key)) continue
    seen.add(key)
    result.push(item)
  }
  return result
}

async function exists(file) {
  try {
    await fs.access(file)
    return true
  } catch {
    return false
  }
}

async function main() {
  if (!(await exists(dataPath))) {
    throw new Error(`Missing ${dataPath}. Run npm run migrate:extract first.`)
  }

  const data = JSON.parse(await fs.readFile(dataPath, 'utf8'))
  const assets = uniqueBy(data.images || [], item => item.src).map(item => ({
    src: item.src,
    alt: item.alt || '',
    width: item.width || null,
    height: item.height || null
  }))

  const anchors = uniqueBy(data.anchors || [], item => `${item.href}|${item.text}`).filter(item => item.text || item.href)
  const manifest = {
    source: data.url,
    capturedAt: new Date().toISOString(),
    title: data.title,
    lang: data.lang,
    assets,
    anchors,
    note: 'Generated by scripts/convert-to-nuxt.mjs. Review before production.'
  }

  await fs.writeFile(manifestPath, JSON.stringify(manifest, null, 2))

  if (await exists(cssPath)) {
    const cleaned = await fs.readFile(cssPath, 'utf8')
    if (cleaned.trim()) {
      await fs.writeFile(targetCssPath, cleaned)
      console.log(`Updated ${targetCssPath} from cleaned runtime CSS.`)
    }
  }

  console.log(`Wrote asset manifest to ${manifestPath}`)
  console.log('Review generated files, then decompose content into Vue components as needed.')
}

main().catch(error => {
  console.error(error.message)
  process.exit(1)
})
